trigger:
- master

resources:
- repo: self

variables:
  OSVersion: '1803'
  OctopusVersion: '2018.11.0'
  ContainerRegistryName: 'cjcreativetech'
  ServerImageName: 'octopusdeploy'
  TentacleImageName: 'workertentacle'

jobs:
- job: OctopusServer

  pool:
    vmImage: 'win1803'

  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: cjcreativetech
      useDefaultContext: false
      buildContext: ./      
      dockerFile: Server/Dockerfile
      arguments: '--build-arg SERVERCORE_VERSION=$(OSVersion) --build-arg OctopusVersion=$(OctopusVersion)'
      imageName: '$(ContainerRegistryName)/$(ServerImageName):$(OSVersion)-$(OctopusVersion)'
      qualifyImageName: false
      includeLatestTag: true

  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: cjcreativetech
      command: 'Push an image'
      imageName: '$(ContainerRegistryName)/$(ServerImageName):$(OSVersion)-$(OctopusVersion)'
      qualifyImageName: false

- job: Tentacle

  pool:
    vmImage: 'win1803'

  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: cjcreativetech
      useDefaultContext: false
      buildContext: ./      
      dockerFile: Tentacle/Dockerfile
      arguments: '--build-arg SERVERCORE_VERSION=$(OSVersion)'
      imageName: '$(ContainerRegistryName)/$(TentacleImageName):$(OSVersion)'
      qualifyImageName: false
      includeLatestTag: true

  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: cjcreativetech
      command: 'Push an image'
      imageName: '$(ContainerRegistryName)/$(TentacleImageName):$(OSVersion)'
      qualifyImageName: false
      
