trigger:
- refs/heads/selfhosted

resources:
- repo: self

variables:
  OSVersion: 'ltsc2019'
  OctopusVersion: '2018.11.3'
  ContainerRegistryName: 'creativedocker'
  ServerImageName: 'octopusdeploy'
  TentacleImageName: 'workertentacle'

jobs:
- job: OctopusServer

  pool:
    name: Default
    
  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: $(ContainerRegistryName)
      useDefaultContext: false
      buildContext: ./      
      dockerFile: Server/Dockerfile
      arguments: '--build-arg SERVERCORE_VERSION=$(OSVersion) --build-arg OctopusVersion=$(OctopusVersion)'
      imageName: '$(ContainerRegistryName)/$(ServerImageName):$(OSVersion)-$(OctopusVersion)'
      qualifyImageName: false
      includeLatestTag: true

  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: $(ContainerRegistryName)
      command: 'Push an image'
      imageName: '$(ContainerRegistryName)/$(ServerImageName)'
      qualifyImageName: false

- job: Tentacle

  pool:
    name: Default
    
  steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: $(ContainerRegistryName)
      useDefaultContext: false
      buildContext: ./      
      dockerFile: Tentacle/Dockerfile
      arguments: '--build-arg SERVERCORE_VERSION=$(OSVersion)'
      imageName: '$(ContainerRegistryName)/$(TentacleImageName):$(OSVersion)'
      qualifyImageName: false
      includeLatestTag: true

  - task: Docker@1
    displayName: 'Push an image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: $(ContainerRegistryName)
      command: 'Push an image'
      imageName: '$(ContainerRegistryName)/$(TentacleImageName)'
      qualifyImageName: false
      
